- name: install and run nginx
  hosts: web
  become: yes #givng root access like in adhoc commands
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
        name: nginx
        state: latest
  - name: start nginx
    ansible.builtin.service:
        name: nginx 
        state: started
        enabled: yes
      
  
