- name: variables from files
  hosts: localhost
  tasks:
    - name: learning devops
      vars:
      -vars.yaml
      ansible.builtin.debug:
      msg: "i am learning {{course}} from {{trainer}} for {{time}}"