- name: variables from files
  hosts: localhost
  tasks:
    vars:
   -vars.yaml
   - name: learning devops
    ansible.builtin.debug:
     msg: "i am learning {{course}} from {{trainer}} for {{time}}"