- name: variables from files
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
  - name: writing vars 
    ansible.builtin.debug:
     msg: "i am learning {{course}} from {{trainer}} for {{time}}"
    