- name: variables from files
  hosts: localhost
  tasks:
  - name: writing vars 
    vars:
    - vars.yaml
    ansible.builtin.debug:
     msg: "i am learning {{course}} from {{trainer}} for {{time}}"
    