- name: variables 
  hosts: localhost
  tasks:
   vars:
    course: "devops"
    trainer: "soma"
    time: "15"
  - name: writing vars 
    ansible.builtin.debug:
     msg: "i am learning {{course}} from {{trainer}} for {{time}}"