- name: vars from prompt
  hosts: localhost
  vars_prompt:
  - name: USER
    prompt: please provide user
    private: yes
  - name: PASSWORD
    prompt: please provide password
    private: false
  tasks: 
  - name: provide information
    ansible.builtin.debug:
     msg: "please provide {{USER}}, and {{PASSWORD}}"