- name: conditoins
  hosts: localhost
  become: yes
  tasks:
  - name: check user exists
    ansible.builtin.command: id EXPENSE
    register: USER
    ignore_errors: yes

  - name: print user information 
    ansible.builtin.debug:
     msg: "user info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0  #conditions
 

  