- name: check number 
  hosts: localhost
  vars_propmt:
    - name: number
      prompt: please enter number
      private: no
  tasks:
    - name: check number less than 10
      ansible.builtin.debug:
        msg: "given number {{number}} is less than 10"
        when: number < 10

    - name: check number greater than 10
      ansible.builtin.debug:
        msg: "given number {{number}} is greater than 10"
        when: number > 10