- name: default value
  hosts: localhost
  tasks:
  - name: default value 
    ansible.builtin.debug:
     msg: "i am learning {{ course | default('devops') }}"

- name: uppercase
  hosts: localhost
  vars:
   greetings: "hi, goodmorning"
  tasks:
  - name: change to uppercase
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"